# fly.toml app configuration file generated for skincareandmore on 2024-08-26T19:26:40+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'skincareandmore'
primary_region = 'sea'

[build]
  image = 'adeyomola/sm'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
