# fly.toml app configuration file generated for skincareandmore-mysql on 2024-08-26T19:05:25+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'skincareandmore-mysql'
primary_region = 'sea'

[build]
  image = 'adeyomola/verba-mysql'

[processes]
  app = '--datadir /data/mysql --default-authentication-plugin caching_sha2_password --performance-schema=OFF --innodb-buffer-pool-size 64M'

[[mounts]]
  source = 'skincareandmoredata'
  destination = '/data'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
  processes = ['app']
